#Python - Non-technical introduction

##Day 4 Session 3 "No data, no problem: How to simulate data?"

This file accompanies the lectures and provides the code for the corresponding slides.

*Note:* If you want to make changes to this document, you need to save your own copy using the "Save copy in Drive" command in the "File" menu.

###Preparation

**Make sure to run the follwing code before continuing.** Code will prepare everything (load data, ...).

In [ ]:
#load the numpy package
import numpy as np
#load the Pandas package
import pandas as pd
#install names package
!pip install names

#Read the csv file and store it in the variable "myData". Note: this file is hostes in a GitHub repository.
myData=pd.read_csv(filepath_or_buffer="https://raw.githubusercontent.com/bachmannpatrick/Python-Class/master/data/transactions.csv", sep=",")
#Adjust the format of column "TransDate" to datetime
myData["TransDate"]  = pd.to_datetime(myData["TransDate"], dayfirst=True)

     |████████████████████████████████| 798kB 4.4MB/s 
  Created wheel for names: filename=names-0.3.0-cp36-none-any.whl size=803689 sha256=b3b51d2df0b3a5b3436b2d87f81cfe5c4e08b7fce72ee0ad06927c9aa81811ba
  Stored in directory: /root/.cache/pip/wheels/f9/a5/e1/be3e0aaa6fa285575078fa2aafd9959b45bdbc8de8a6803aeb
Successfully built names


###38 - Creating sequences automatically

####**Slide:** Sequences for equal spacing (1/2)

In [ ]:
#basic sequences
range(2,13)


Customer Gender  Birthdate       ZIP   JoinDate  TransKey
0     42291      m 1963-07-12  US-04533 1998-07-23       NaN
1     42886      f 1987-05-04  US-08055 2011-06-12       NaN
2     80365      f 1991-08-26  US-06332 2009-09-15       NaN

In [ ]:
#arrays
np.arange(start=1, stop=12, step=3)


array([ 1,  4,  7, 10])

In [ ]:
np.arange(start=1.25, stop=6.25, step=0.25)


array([1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75,
       4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  ])

####**Slide:** Sidenote: Unnamed arguments

In [ ]:
np.arange(start=1, stop=12, step=3)

array([ 1,  4,  7, 10])

In [ ]:
np.arange(1,12,3)

array([ 1,  4,  7, 10])

In [ ]:
np.arange(1,3,12)

array([1])

In [ ]:
#use argument names!
np.arange(start=1, step=3, stop=12)

array([ 1,  4,  7, 10])

####**Slide:** Sequences for equal spacing (2/2)

In [ ]:
#Characters
import string

list(string.ascii_lowercase)[0:5]


['a', 'b', 'c', 'd', 'e']

In [ ]:
#Dates

pd.date_range(start='1/1/2011',end='03/31/2011',
freq="MS")

DatetimeIndex(['2011-01-01', '2011-02-01', '2011-03-01'], dtype='datetime64[ns]', freq='MS')

####**Slide:** Replicate a number or vector

In [ ]:
#Continuous replications
np.tile(range(1,13), reps=3)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10, 11, 12,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,
       11, 12])

In [ ]:
#Consecutive repetitions
np.repeat(range(1,13), repeats=3)


array([ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  6,  6,
        6,  7,  7,  7,  8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11, 12,
       12, 12])

####**Slide:** Create a table with all possible permutations of the given variables

In [ ]:
import itertools
list(itertools.product(range(165,168), ["1", "2"]))

[(165, '1'), (165, '2'), (166, '1'), (166, '2'), (167, '1'), (167, '2')]

In [ ]:
#An example
CustId = range(165,168)
Store= ["A","B"]
CustData= pd.DataFrame(list(itertools.product(CustId, Store)))
CustData.columns = ["CustId", "Store"]
CustData

CustId Store
0     165     A
1     165     B
2     166     A
3     166     B
4     167     A
5     167     B

####**Slide:** Sidenote: Concatenate strings

In [ ]:
CustData.head(n=3)
CustData.dtypes
CustData["Store_Cust"] = CustData["CustId"].astype(str) + "_" + CustData["Store"].astype(str)
CustData.head(n=3)

CustId Store Store_Cust
0     165     A      165_A
1     165     B      165_B
2     166     A      166_A

####**Slide:** Sidenote: Finding unique elements

In [ ]:
#Return the unique entries of a DataFrame

CustData.drop_duplicates()

CustId Store Store_Cust
0     165     A      165_A
1     165     B      165_B
2     166     A      166_A
3     166     B      166_B
4     167     A      167_A
5     167     B      167_B

In [ ]:
#Return the unique elements of a vector

pd.unique(CustData["Store"])

array(['A', 'B'], dtype=object)

###39 - Simulating and manipulating strings

####**Slide:** Random name sampling with `names()` (1/2)

In [ ]:
import names

In [ ]:
randnames=[]
#We use a loop here to show an example. Loops will be discussed tomorrow.
for i in range(3):
  randnames.append(names.get_full_name(gender="female"))
print (randnames)

NameError: ignored

####**Slide:** Random name sampling with `names()` (2/2)

In [ ]:
#Firstnames:
names.get_first_name(gender="female")

'Brenda'

In [ ]:
#Lastnames:
names.get_last_name()

'Perez'

####**Slide:** Manipulate strings in Python

In [ ]:
#Trim leading and trailing whitespaces
"   this is a      test   ".strip()

'this is a      test'

In [ ]:
#Pad strings with zeros to create strings of equal width
ids = [1,12,123,1234]
[str(item).zfill(4) for item in ids]

['0001', '0012', '0123', '1234']

In [ ]:
#Search for strings in a vector
friends = ['Nicholas', 'Thomas', 'Kayla']
["Nicholas" in item for item in friends]

[True, False, False]

In [ ]:
#Observe, that list comprehension provides a vectorized output in contrast to:
"Nicholas" in friends

True

In [ ]:
#Replace string in a vector
[item.replace("Nicholas", "Nicki") for item in friends]


['Nicki', 'Thomas', 'Kayla']

In [ ]:
#Caution: The replace()-function is case sensitive
[item.replace("nicholas", "Nicki") for item in friends]

['Nicholas', 'Thomas', 'Kayla']

In [ ]:
#Transform strings to lower case
[item.lower() for item in friends]

['nicholas', 'thomas', 'kayla']

In [ ]:
#Transform strings to upper case
[item.upper() for item in friends]

['NICHOLAS', 'THOMAS', 'KAYLA']

####**Slide:** Advanced string manipulation:
Use the `split()`-function

In [ ]:
#Split strings
firstname=randnames[0]
print(firstname)
print(firstname.split(" ",1))
print(firstname.split(" ",1)[0])

Patricia Gill
['Patricia', 'Gill']
Patricia


In [ ]:
#Split lists of strings
print(randnames)
print([i.split(" ",1)[0] for i in randnames])

['Patricia Gill', 'Betty Wier', 'Shirley Pepper']
['Patricia', 'Betty', 'Shirley']


####**Slide:** Advanced string manipulation:
 Anonymize customer names (and IDs)

In [ ]:
list(map(hash, CustData["CustId"]))

[165, 165, 166, 166, 167, 167]

###40 - Simulating variables by using distributions

####**Slide:** Discrete distribution simulation in Python

In [ ]:
#without replacement
np.random.choice(10, size=5, replace=False)

array([9, 0, 1, 2, 7])

In [ ]:
#with replacement
np.random.choice(10, size=5, replace=True)

array([1, 9, 2, 1, 8])

####**Slide:** Continuous distribution simulation in Python

In [ ]:
np.random.normal(loc=5.0, scale=1.0, size=500)

array([3.36769746, 6.13266398, 4.42877175, 4.30282551, 4.41155579,
       5.28231082, 6.07695258, 4.75405302, 6.73074229, 2.78181193,
       4.48266352, 4.58101573, 3.86594392, 5.31401877, 4.91432484,
       5.74602525, 5.23116526, 2.67333636, 4.04880078, 5.36190081,
       5.05643163, 4.32505254, 5.98288353, 4.6003676 , 5.0346396 ,
       3.26163587, 5.04468595, 5.71750734, 4.2998289 , 5.20746189,
       3.48821181, 5.71043785, 6.28514469, 7.07628561, 3.92318679,
       3.84718169, 6.22679335, 4.14942192, 4.12871372, 4.7650099 ,
       4.48443485, 5.9213178 , 4.40631385, 4.89883709, 6.66725314,
       4.40636743, 4.9088805 , 5.43301637, 4.82726964, 6.42115777,
       3.79447218, 4.26257466, 3.79156687, 4.19458525, 5.27598515,
       4.90280351, 4.99222249, 5.4497079 , 6.73946873, 5.42538027,
       4.71505797, 5.35464074, 5.69954984, 6.27912066, 5.81325304,
       4.22579624, 5.37214573, 5.87680044, 6.42211645, 7.34330001,
       4.74740667, 5.88086101, 5.9773079 , 3.01609046, 4.03400

####**Sidenote:** Sidenote: Setting seeds to recreate the same numbers

In [ ]:
print(np.random.normal(size=5))
print(np.random.normal(size=5))

[-1.31418325  0.94220128  1.21402604  1.98173522  1.54487031]
[ 0.15069935 -0.98538719 -0.00545831  0.31898334  1.84812018]


In [ ]:
#with seed
np.random.seed(1)
print(np.random.normal(size=5))

np.random.seed(1)
print(np.random.normal(size=5))
#Caution: you have to set the seed everytime (!)

[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
